add some preflight checks to ./apply helpers

diff --git a/infra/examples-dev/gcp/apply b/infra/examples-dev/gcp/apply
--- a/infra/examples-dev/gcp/apply
+++ b/infra/examples-dev/gcp/apply
@@ -4,6 +4,23 @@
 if [ -d "${PWD}/.azure" ]; then
     export AZURE_CONFIG_DIR="${PWD}/.azure"
 fi
+
+printf "Running preflight auth checks...\n"
+
+if ! gcloud auth print-access-token &> /dev/null; then
+  printf "\033[0;31mERROR: Google Cloud CLI is not authenticated or token is expired.\033[0m\n"
+  printf "Please run 'gcloud auth login' and/or 'gcloud auth application-default login' before applying.\n"
+  exit 1
+fi
+
+if grep -E "^msft_tenant_id" terraform.tfvars &> /dev/null; then
+  if ! az account show &> /dev/null; then
+    printf "\033[0;31mERROR: Azure CLI is not authenticated but msft_tenant_id is set in terraform.tfvars.\033[0m\n"
+    printf "Please run './az-auth' to authenticate before applying.\n"
+    exit 1
+  fi
+fi
+
 # prompt if user wants to force_bundle or not; default to Y
 read -p "Do you want to force rebuild of the bundle? (eg, have you made java code changes?) (Y/n): " force_bundle
 
